### ISSUE TITLE
`npm ERR! could not determine executable to run` when trying to install

### ISSUE THREAD

**Issue by komali2** [ElianCodes/brutal#103]
**Describe the bug**

When trying to install project via `npx create astro@latest -- --template eliancodes/brutal`, I get the error:

`npm ERR! could not determine executable to run`

**Minimal example**
Link to minimal example: 
https://github.com/ElianCodes/brutal

**Expected behavior**

**Screenshots**

**Additional context**

npm version `10.2.4`
node version `v20.11.0`

**Comment by ElianCodes** [comment]
ah yeah, this behaviour changed. Can you try if `npm create astro@latest -- --template eliancodes/brutal` works for you?

**Comment by komali2** [comment]
Yes, that worked!
