### ISSUE TITLE
Adding a license to the repository

### ISSUE THREAD

**Issue by Topfi** [ElianCodes/brutal#26]
**Is your feature request related to a problem? Please describe.**

Very much enjoying your template, but I was wondering whether you could add a license to it, as that ensures that people are aware on in what capacity they may rely on and modify this project.

**Describe the solution you'd like**

I'd suggest adding a simple MIT license, as that allows for the reuse and modification of the template by others without restrictions. The MIT license is also utilized by most other templates showcased on the Astro.build website, so it'd like fit well as users may already be used to other templates being licensed with MIT.

There are also 0BSD and Apache 2.0, both similarly permissive to MIT, though with some subtle differences that are unlikely to make a discernible difference for users compared to MIT in this case.

If you'd prefer retaining more control, there are also more restrictive licenses like LGPL, GPL and the EUPL, all with their own up- and downsides, though generally these should more broadly ensure that changes made to your code are made accessible.

**Additional context**

Beyond licensing, some website template project also ask users to keep a reference and link to the original project (kindly provided by) visible when hosting the page, with the option to donate/pay to be allowed to remove that. Perhaps this could be an option here as well.

**Comment by ElianCodes** [comment]
Hey! Thanks for the issue! I've added the license under `.github/LICENSE`!
