### ISSUE TITLE
Hamburger menu

### ISSUE THREAD

**Issue by gwisk** [ElianCodes/brutal#28]
**Is your feature request related to a problem? Please describe.**

N/A

**Describe the solution you'd like**

Hi Elian! Loving the theme — it's absolutely brilliant. I saw that on your personal site, you've added a hamburger menu to the mobile layout. It looks like astro-navbar, and I've tried adding that, but I'm having some difficulty with the layout. I was wondering if you wouldn't mind sharing your code for the hamburger menu implementation. Thank you!

**Comment by ElianCodes** [comment]
hey @gwisk! Thanks for opening an issue!

The reason I didn't add one in the Brutal theme itself, is to don't force a framework choice upon the users. In my own website I use Astro's Vue integration. Here's a link to the component: https://github.com/ElianCodes/ElianCodes-frontend/blob/main/src/components/layout/MobileNavigation.vue

Hope this helps!

**Comment by gwisk** [comment]
Thank you, Elian! I appreciate the help, and thanks again for the great theme.
