### ISSUE TITLE
Twitter Card preview is broken

### ISSUE THREAD

**Issue by gwisk** [ElianCodes/brutal#29]
**Describe the bug**

Twitter provides devs the ability to show cards when website links are posted on Twitter by using meta tags in the header. The theme provides these tags, but the card preview is broken.

I first noticed this on my own site which I've deployed, and I checked this issue exists with the original template website (www.brutal.elian.codes). It doesn't exist on your personal website, which works fine. I've tried updating the tags on my deployed site to match what you have on your personal site, but no luck. 

**Minimal example**
Go to Twitter and paste the link to the template site and compare with the main site (www.elian.codes). Screenshots are below.

**Screenshots**
<img width="535" alt="Screenshot 2023-07-11 at 11 31 17 AM" src="https://github.com/ElianCodes/brutal/assets/20115873/ab1853a3-7367-4f64-ba3c-a1a3fded57e6">
<img width="535" alt="Screenshot 2023-07-11 at 11 31 29 AM" src="https://github.com/ElianCodes/brutal/assets/20115873/af325504-9e12-40d4-b44b-1d2bf6463a0a">

Any advice/fixes would be super great! Thank you, Elian!

**Comment by ElianCodes** [comment]
Hey, I just checked this. You're totally right, It seems that Twitter doesn't work with SVG images as social cards. On my own website I convert them to PNG from the SVG. 

I totally can look into it; But if you're up for making a PR for this, feel free to do so!

**Comment by gwisk** [comment]
HI Elian, I'm continuing to investigate — the problem on my end is that even when I convert to .png (I copied the [slug].png.ts and default.png.ts files from your personal site), the cards still don't preview as expected. I'm trying to see if it's an issue with how the site is being crawled/deployed, but if you had any insight, do leet me know. If I do manage to fix it, I'll issue a PR!

**Comment by gwisk** [comment]
Hi Elian! Yes, managed to fix it. Twitter has been quite buggy with cards (also seems their backend has a cache of ~ a week, so changes are not immediate, which makes checking changes difficult in light of the Twitter Card Validator being deprecated), but I managed to verify just pulling files from your personal site worked. Made a pull request to reflect these changes. Thank you!

**Comment by ElianCodes** [comment]
Thanks for your issue and work on it!

Solved & fixed!
