### ISSUE TITLE
Change Favicon to Astro default

### ISSUE THREAD

**Issue by ElianCodes** [ElianCodes/brutal#4]

**Comment by vasfvitor** [comment]
Links from Astro repo
[favicon.ico ](https://github.com/withastro/astro/blob/main/packages/astro/test/fixtures/ssr-dynamic/public/favicon.ico)
[favicon.svg](https://github.com/withastro/astro/blob/main/examples/ssr/public/favicon.svg)

**Comment by ElianCodes** [comment]
Hehe, I perfectly know where they are located 😉 just haven't found the time to update the codebase!
