### ISSUE TITLE
Back to top button seems to dissapear on mobile devices

### ISSUE THREAD

**Issue by ElianCodes** [ElianCodes/brutal#47]
**Describe the bug**

As reported by user @emish89, the back to top inner icon seems to disappear on iOS and MacOS Safari

**Minimal example**
![image](https://github.com/ElianCodes/brutal/assets/15145918/89dbde5b-b12c-4b66-8511-d434bc6041f1)

**Comment by emish89** [comment]
thanks for creating it. 

I investigated a bit and I have to say that this bug is not related to mobile but to iOS and MacOS Safari

**Comment by ElianCodes** [comment]
Good to know! I'll investigate further when I have some spare time!

**Comment by emish89** [comment]
me too

**Comment by ElianCodes** [comment]
In case you get to it before I do, feel free to open a PR!

**Comment by ElianCodes** [comment]
That's awesome! Feel free to open a PR for that! (or if you rather have me do it, that's fine too!)
