### ISSUE TITLE
Missing fonts on site

### ISSUE THREAD

**Issue by at-the-vr** [ElianCodes/brutal#49]
**Describe the bug**
- Fonts are missing when using the template
- 404 Errors come in terminal for all fonts

**Minimal example**

This issue does not generate on Stackblitz or even GitPod but only Local Devices with the template or forks

**Steps to reproduce**
1. Fork the repo `OR` Create a new repo by clicking on `Use this template`
2. open the repo/fork on your local device, `pnpm i` && `pnpm dev`
3. Issue comes

> The issue can also be reproduced in build & preview

**Expected behavior**
- Fonts would render just fine

**Screenshots**
![image](https://github.com/ElianCodes/brutal/assets/88548999/ee0a6fa5-6a2f-41f3-b4b0-ab940e2deb49)
![image](https://github.com/ElianCodes/brutal/assets/88548999/736f94ac-2060-45da-8e76-67bae9076319)

**Additional context**

**Comment by ElianCodes** [comment]
Hmm, that's weird, everything seems to work for me tho.

**Comment by at-the-vr** [comment]
i suppose the issue can be closed (i had to remove astro-font changes for it to work anyways)
this can be reconsidered to open when more users face this issue
