### ISSUE TITLE
Missing OG Images for Blog posts

### ISSUE THREAD

**Issue by at-the-vr** [ElianCodes/brutal#50]
**Describe the bug**
- OG Images for blogposts have an incorrect format in the meta tag (it shows as .svg instead of .png)

**Minimal example**

[Blog Post 2 on Brutal](https://brutal.elian.codes/blog/blogpost-2/)

**Expected behavior**

Show correct OG [image for blogpost 2](https://brutal.elian.codes/v1/generate/og/blogpost-2.png)

 **Screenshots**

![image](https://github.com/ElianCodes/brutal/assets/88548999/ae041cb6-9563-4a09-9deb-4cd29246f588)

**Additional context**

**Comment by at-the-vr** [comment]
Turns out its just a typo here

https://github.com/ElianCodes/brutal/blob/da5b0f0999d311215a88e7c93533bfcae66bbd0e/src/layouts/BlogPost.astro#L7

**Comment by ElianCodes** [comment]
Thanks for opening an issue!

Feel free to open a PR to fix this, in case you can't, I can do it tomorrow!
