### ISSUE TITLE
Fonts error

### ISSUE THREAD

**Issue by juanandres-montero** [ElianCodes/brutal#71]
**Can't load any font**
My terminal shows (when `pnpm dev` the original template without edits):

16:33:53 [404] /fontspoppins.ttf 45ms
16:33:53 [404] /fontsrighteous.ttf 46ms
16:33:53 [404] /fontsoutfit.ttf 47ms
16:33:53 [404] /fontssanchez.ttf 48ms
16:33:53 [404] /fontsm-serif.ttf 12ms

I have tried to use directs urls to the fonts in the LocalFont.astro file.

**Comment by rishi-raj-jain** [comment]
Hey @juanandres-montero,

May you share the minimal reproduction and your OS environment?

**Comment by juanandres-montero** [comment]
I didn't include them in the css document, it's fixed

Thanks!
